version: '3'

services:

  mysql:
    image: mysql:5.7
    container_name: hive_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: metastore
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql


  hive:
    image: apache/hive:4.0.0
    container_name: hive_server
    depends_on:
      - mysql
    environment:
      SERVICE_NAME: hiveserver2
    ports:
      - "10000:10000"
      - "10002:10002"
    volumes:
      - ./warehouse:/opt/hive/data/warehouse


volumes:
  mysql_data:
